/*
 * TomiSoft DateTime Test Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using DateTimeMicroservice.Server.OpenApiGenerated.Attributes;
using Microsoft.AspNetCore.Authorization;
using DateTimeMicroservice.Server.OpenApiGenerated.Models;

namespace DateTimeMicroservice.Server.OpenApiGenerated.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DateTimeApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Gets the server&#39;s current date-time in UTC format</remarks>
        /// <response code="200">Represents the response of /currentTime API path</response>
        [HttpGet]
        [Route("/currentTime")]
        [ValidateModelState]
        [SwaggerOperation("CurrentTimeGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(DateTimeObject), description: "Represents the response of /currentTime API path")]
        public virtual IActionResult CurrentTimeGet()
        { 

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(DateTimeObject));
            string exampleJson = null;
            exampleJson = "{\r\n  \"dateTime\" : \"2000-01-23T04:56:07.000+00:00\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<DateTimeObject>(exampleJson)
            : default(DateTimeObject);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
